site_name: prsWorkshop
repo_url:  https://github.com/tadesouaiaia/prsWorkshop-website
site_author: Tade Souaiaia 
nav:
    - Home: index.md
    
    - Pre-Workshop: 
      - Checklist:        prep_list.md 
      - System:           prep_os.md 
      - Terminal:             prep_terminal.md 
      - Software:         prep_software.md 
      - Testing:         prep_testing.md 
        
    - Program: 
       - Information: prog_comingsoon.md
    #  - Day 1a:  Day2.docx.md 
    #  - Day 1b: Day3a.docx.md
    #      - Day 2ac: Day3b.docx.md 
    #      - Day 2b: Day4a.docx.md 

    - Tutorials: 
        - Bash Tutorial:           misc_commands.md 
        - R Tutorial:              misc_R.md 
        - Python Tutorial:         misc_python.md 
#        - Plink Tutorial:          misc_plink.md 
        
    - Misc:
        - Linux For Windows:      misc_linux.md 
        - Mac Security:            misc_plink_problem.md 





theme:
    name: readthedocs 
extra_css: [css/extra.css]
palette: 
accent: deep orange
highlightjs: false

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.highlight:
        use_pygments: true
        noclasses: true
    - pymdownx.arithmatex:
        generic: True
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - javascripts/details.js

